### PR TITLE
Import of spoonerism example

### PR DESCRIPTION
**Pull request by alshopov**
Signed-off-by: Alexander Shopov <ash@kambanaria.org>

### CODE REVIEW

**Comment by monperrus** [comment]
Really nice, thanks :-)

Could you translate `spoonerism.odp` to `spoonerism.fodp` (fodp is appropriate for Git)?

Could you add an explanatory line in the README?

Thanks!

**Comment by alshopov** [comment]
Check again

**Comment by monperrus** [comment]
Thanks a lot!

**Comment by alshopov** [comment]
It was a pleasure and honor

**Pull request merged**
